
out='results'

font(
	target=process("MiaoUnicode.ttf"),
	source="source/miao.sfd",
    graphite=gdl("miao.gdl", master="source/miao.gdl", params="-d -q -w3521", make_params="-r"),
    script = 'plrd'
    )
